### ISSUE TITLE
bug: Re-running the cell creating the session leads to race conditions

### ISSUE THREAD

**Issue by bjchambers** [kaskada-ai/kaskada#267] opened 2023-04-21 21:25 UTC
**Description**
This seems to be because the session is closed when it is garbage collected (probably good) but it uses global state (probably bad) so that instead of closing the *old* session it closes the *new* session (definitely bad).

**To Reproduce**
Have a cell in a notebook like:

```
# Create the Kaskada Session
from kaskada.api.session import LocalBuilder
session = LocalBuilder().build()
```

Note that without the `session =` the session is *immediately* closed because it is garbage collected right away.

Run the cell.

Rerun the cell.

**Actual Behavior**
A new session is started and immediately closed.

**Expected Behavior**
When the cell is rerun the *previous* session is closed and a new session is started.

**Comment by bjchambers** [comment] 2023-04-21 21:26
We can work around the problem by changing the cell to something like:

```
# Create the Kaskada Session
from kaskada.api.session import LocalBuilder
session = None

import gc
gc.collect()

session = LocalBuilder().build()
```

Which is not guaranteed to work, but supports the suspicion that this is because the old session is deleted after the new session is created.

**Comment by bjchambers** [comment] 2023-04-21 21:27
We should probably hold the PID in the session itself, so we only delete the current session when it is dropped. @kevinjnguyen thoughts?

**Comment by kevinjnguyen** [comment] 2023-05-01 22:41
Thanks @bjchambers for reporting this issue. It definitely seems like a bug with regards to the session management. I've done some initial investigation on why this is happening. You are correct that the session closing automatically happens at garbage collection and this is done by implementing the `__del__` method [here](https://github.com/kaskada-ai/kaskada/blob/main/clients/python/src/kaskada/api/session.py#L36). 


> Note that without the session = the session is immediately closed because it is garbage collected right away.

This is correct. After the code is executed, the reference count of the session is now 0 once the cell completes execution and the garbage collection should kick in. 

> Run the cell. Rerun the cell.

This is correct. If we assign the session to the `session` variable, then re-run the cell, the result is that no service is running at all. When we re-run the cell, a new `session` variable is created by trying to run the subprocesses. These two processes most likely fail with a port already in use error and fail to launch. Since the processes never return/are continuously running, we establish a connection to the services by polling 50051/50052. But the client is able to connect to the previous session since the garbage collection has not occurred yet. Once the re-run completes and the session re-assignment is complete, the previous `session` reference count is now 0 thus triggering the garbage collection to kill the manager/engine. This results in the old session terminated and the new session failing to connect since it connected to the old process.

**Comment by kevinjnguyen** [comment] 2023-05-01 22:54
> We should probably hold the PID in the session itself, so we only delete the current session when it is dropped. @kevinjnguyen thoughts?

We already do store a reference to the original process that was executed (see [Popen](https://docs.python.org/3/library/subprocess.html#subprocess.Popen)). On the garbage collection, the `kill` method is called on these processes.

I believe the confusion here is that the new processes are failing to start because the existing services have not been killed yet. A suggestion for resolution of the issue is to manage a reference to the sessions as part of the Kaskada API Session module. When a new session is created, first check to see if an existing session exists for the requested ports (50051/50052 by default). If they already exist, then call the garbage collector on the existing session prior to starting up the new one. Then once the session is started, store the new session in the existing sessions.

Suggested work:
* Update the `session.py` module to store the existing sessions by port mapping. 50051 and 50052 -> session.
* Update session creation to check if the requested ports 50051 or 50052 already have created a session.
  * If the session already exists, then call the delete on the existing session.
* Create the new session and store it in the mapping.

Does this work with you? @bjchambers

**Comment by kevinjnguyen** [comment] 2023-05-24 01:13
The latest PR #373 iterates on the next implementation of the Local Session to automatically recover from local session failure. Please take a look at this [example notebook](https://github.com/kaskada-ai/kaskada/blob/main/examples/Local%20Session%20(Next%20Iteration).ipynb) for a documented feature rundown.

**Closed by kevinjnguyen** 2023-05-24 01:13 UTC
Labels: bug, python, p1
