### ISSUE TITLE
bug: Diagnostics are right-aligned in notebooks 

### ISSUE THREAD

**Issue by bjchambers** [kaskada-ai/kaskada#312] opened 2023-05-03 17:30 UTC
**Description**
When running a Jupyter notebook, the Fenl diagnostics were shown right aligned... which makes them hard to read.

**To Reproduce**
Run a query with a syntax error.

**Actual Behavior**
<img width="1004" alt="Screen Shot 2023-05-03 at 10 28 25 AM" src="https://user-images.githubusercontent.com/35960/235996339-a65f2ceb-a65b-4eae-b031-42cfb76615b0.png">

**Expected Behavior**
Diagnostics are left aligned.

**Additional context**
This was a notebook running in VScode.

The expression (in the details) also appears as right justified.

**Comment by kevinjnguyen** [comment] 2023-05-03 22:09
@bjchambers have you verified this is not a user IDE issue? On my end, I am not able to reproduce this error. 

Running it on VSCode:
<img width="1695" alt="Screenshot 2023-05-03 at 5 07 16 PM" src="https://user-images.githubusercontent.com/15032894/236060538-a9d3954e-bfa4-4705-aa6d-124cc720fb55.png">

Running it on Jupyter:
<img width="1104" alt="Screenshot 2023-05-03 at 5 08 38 PM" src="https://user-images.githubusercontent.com/15032894/236060724-fe844093-d3f5-4c83-a4c1-7c9df17910ff.png">

**Comment by kevinjnguyen** [comment] 2023-05-08 22:50
This does not appear to be an issue so going ahead and closing this.

**Closed by kevinjnguyen** 2023-05-08 22:50 UTC
Labels: bug
