### ISSUE TITLE
feat: Add documentation of the Python library

### ISSUE THREAD

**Issue by kerinin** [kaskada-ai/kaskada#252] opened 2023-04-20 19:20 UTC
**Summary**
Currently the only way to discover function parameters or return type structure is to dig through the source code.

**Comment by bjchambers** [comment] 2023-04-20 20:07
I believe this may be a duplicate of #220. Does that sound right @therapon?

**Comment by therapon** [comment] 2023-04-20 20:10
Yes #220 should resolve this issue as well

**Closed** 2023-04-21 15:55 UTC
Labels: enhancement, user-study
